### ISSUE TITLE
Obscure doco

### ISSUE THREAD

**Issue by PhilHudson** [rougier/pdf-drop-mode#3]
What's a DOI?

**Comment by elken** [comment]
> What's a DOI?

https://en.wikipedia.org/wiki/Digital_object_identifier first result on duckduckgo :smile:

**Comment by PhilHudson** [comment]
Yes. The point is that you don't document it.

Look me in the eye, put your hand on your heart, and tell me that you would
lose something important by documenting it. Hey, maybe you could even put
one of those modern hyperlink things in behind the acronym expansion. But
no, rather than do that and close the issue, you sent it to just me instead.

**Comment by elken** [comment]
> Yes. The point is that you don't document it.

Me? It's not my package. 

As I pointed out to you another time you did this, the package is clearly WIP. Posting a very poorly formed issue isn't the way to "try to contribute in small ways when I can".

Please kindly unlearn this habit, all you're doing is creating noise for package maintainers :)
